import { 
  Heart, Shield, Sword, Zap, Skull, Flame, Star, Sun, Moon, Cloud, 
  Droplet, Snowflake, Wind, TreePine, Leaf, Bug, Bird, Cat, Dog, Fish, Rabbit, 
  Turtle, Car, Plane, Anchor, Rocket, Crown, Gem, Ghost, Music, Gamepad, Coffee, 
  Beer, Apple, Carrot, Pizza, Tent, Mountain, Camera, Eye, Map, Compass, Bell, 
  Book, Briefcase, Calculator, Calendar, Cherry, Clover, Cpu, Crosshair, Feather,
  Flag, Flower2, Hammer, Key, Lightbulb, Magnet, Palmtree, Scissors,
  Trophy, Umbrella, Wrench
} from 'lucide-react';

export const COMMON_ICONS = [
  { name: 'Heart', icon: Heart },
  { name: 'Shield', icon: Shield },
  { name: 'Sword', icon: Sword },
  { name: 'Zap', icon: Zap },
  { name: 'Skull', icon: Skull },
];

export const ALL_ICONS = [
  ...COMMON_ICONS,
  { name: 'Flame', icon: Flame },
  { name: 'Star', icon: Star },
  { name: 'Sun', icon: Sun },
  { name: 'Moon', icon: Moon },
  { name: 'Cloud', icon: Cloud },
  { name: 'Droplet', icon: Droplet },
  { name: 'Snowflake', icon: Snowflake },
  { name: 'Wind', icon: Wind },
  { name: 'TreePine', icon: TreePine },
  { name: 'Leaf', icon: Leaf },
  { name: 'Bug', icon: Bug },
  { name: 'Bird', icon: Bird },
  { name: 'Cat', icon: Cat },
  { name: 'Dog', icon: Dog },
  { name: 'Fish', icon: Fish },
  { name: 'Rabbit', icon: Rabbit },
  { name: 'Turtle', icon: Turtle },
  { name: 'Car', icon: Car },
  { name: 'Plane', icon: Plane },
  { name: 'Anchor', icon: Anchor },
  { name: 'Rocket', icon: Rocket },
  { name: 'Crown', icon: Crown },
  { name: 'Gem', icon: Gem },
  { name: 'Ghost', icon: Ghost },
  { name: 'Music', icon: Music },
  { name: 'Gamepad', icon: Gamepad },
  { name: 'Coffee', icon: Coffee },
  { name: 'Beer', icon: Beer },
  { name: 'Apple', icon: Apple },
  { name: 'Carrot', icon: Carrot },
  { name: 'Pizza', icon: Pizza },
  { name: 'Tent', icon: Tent },
  { name: 'Mountain', icon: Mountain },
  { name: 'Camera', icon: Camera },
  { name: 'Eye', icon: Eye },
  { name: 'Map', icon: Map },
  { name: 'Compass', icon: Compass },
  { name: 'Bell', icon: Bell },
  { name: 'Book', icon: Book },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Calculator', icon: Calculator },
  { name: 'Calendar', icon: Calendar },
  { name: 'Cherry', icon: Cherry },
  { name: 'Clover', icon: Clover },
  { name: 'Cpu', icon: Cpu },
  { name: 'Crosshair', icon: Crosshair },
  { name: 'Feather', icon: Feather },
  { name: 'Flag', icon: Flag },
  { name: 'Flower', icon: Flower2 },
  { name: 'Hammer', icon: Hammer },
  { name: 'Key', icon: Key },
  { name: 'Lightbulb', icon: Lightbulb },
  { name: 'Magnet', icon: Magnet },
  { name: 'Palmtree', icon: Palmtree },
  { name: 'Scissors', icon: Scissors },
  { name: 'Trophy', icon: Trophy },
  { name: 'Umbrella', icon: Umbrella },
  { name: 'Wrench', icon: Wrench }
];
