// Builds one <slug>/index.html per entry in landing/pages.mjs from index.html,
// plus public/sitemap.xml. Run `npm run landing` after changing either file;
// src/test/landingPages.test.ts fails while the committed output is stale.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { landingPages } from '../landing/pages.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://customdiceroller.com';

const escapeAttr = (s) => s
  .replace(/&/g, '&amp;').replace(/"/g, '&quot;')
  .replace(/</g, '&lt;').replace(/>/g, '&gt;');

function replaceOnce(html, from, to) {
  if (!html.includes(from)) throw new Error(`landing-pages: template no longer contains ${from}`);
  return html.replace(from, () => to);
}

const DEFAULT_TITLE = 'Custom Dice Roller — Build and Roll Any Dice Online';
const DEFAULT_DESCRIPTION = 'Free online dice roller for board games and tabletop RPGs. Build custom dice with any faces, colours and icons, then share your set with a link.';

export function renderPage(template, page) {
  const url = `${SITE}/${page.slug}/`;
  const title = escapeAttr(page.title);
  const description = escapeAttr(page.description);
  let html = template;
  html = html.replaceAll(`<title>${DEFAULT_TITLE}</title>`, `<title>${title}</title>`);
  html = html.replaceAll(`content="${DEFAULT_TITLE}"`, `content="${title}"`);
  html = html.replaceAll(`content="${DEFAULT_DESCRIPTION}"`, `content="${description}"`);
  html = replaceOnce(html, `<meta property="og:url" content="${SITE}/" />`, `<meta property="og:url" content="${url}" />`);
  html = replaceOnce(html, `<link rel="canonical" href="${SITE}/" />`, `<link rel="canonical" href="${url}" />`);
  html = replaceOnce(html, '<body>', '<body class="landing">');
  const start = escapeAttr(JSON.stringify({ heading: page.heading, ...page.start }));
  html = replaceOnce(html, '<div id="root"></div>', `<div id="root" data-start="${start}"></div>`);

  const others = landingPages
    .filter(p => p.slug !== page.slug)
    .map(p => `<a href="/${p.slug}/">${p.heading}</a>`)
    .concat('<a href="/">Build your own dice</a>')
    .join(' · ');
  const article = [
    '<!-- Generated from landing/pages.mjs by scripts/landing-pages.mjs. Edit those, not this. -->',
    '<article class="landing-article">',
    `<h2 class="landing-title">${page.heading}</h2>`,
    page.body.trim(),
    `<nav class="landing-more" aria-label="More dice rollers">${others}</nav>`,
    '</article>',
    '<noscript><p class="landing-article">This app needs JavaScript enabled to roll dice.</p></noscript>',
  ].join('\n    ');
  html = html.replace(/<noscript>[\s\S]*?<\/noscript>/, () => article);
  return html;
}

export function renderSitemap(lastmod) {
  const urls = [{ loc: `${SITE}/`, priority: '1.0' }]
    .concat(landingPages.map(p => ({ loc: `${SITE}/${p.slug}/`, priority: '0.8' })));
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/landing-pages.mjs from landing/pages.mjs. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls.map(u => `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`),
    '</urlset>',
    '',
  ].join('\n');
}

export function sitemapLastmod() {
  const current = readFileSync(join(ROOT, 'public/sitemap.xml'), 'utf8');
  return current.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1];
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const template = readFileSync(join(ROOT, 'index.html'), 'utf8');
  for (const page of landingPages) {
    mkdirSync(join(ROOT, page.slug), { recursive: true });
    writeFileSync(join(ROOT, page.slug, 'index.html'), renderPage(template, page));
  }
  const lastmod = process.argv[2] || new Date().toISOString().slice(0, 10);
  writeFileSync(join(ROOT, 'public/sitemap.xml'), renderSitemap(lastmod));
  console.log(`landing-pages: wrote ${landingPages.length} pages and the sitemap (lastmod ${lastmod})`);
}
